version: '3.7'
services:
  notebook:
    build:
      context: ./insight_notebook_docker
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: 'jovyan'
      POSTGRES_PASSWORD: 'letmein'
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - type: bind
        source: ./notebooks
        target: /host
  postgres:
    build:
      context: ./postgresql_docker
    restart: always
    environment:
      POSTGRES_USER: 'jovyan'
      POSTGRES_PASSWORD: 'letmein'
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-insight-store:/var/lib/postgresql/data

volumes:
    postgres-insight-store:
